name: Feature request
description: Suggest an idea or improvement
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Whiskey DB better? Let us know how it would help.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature.
      placeholder: "Allow importing bottles from CSV"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why?
      description: What problem does this solve? Who benefits?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Outline how you imagine it working (UI/API changes, automation, etc.).
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or workarounds
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Mockups, links, or related issues.
