name: Bug report
description: Something isn’t working as expected
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Whiskey DB! Please share as much detail as you can.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong? Keep it short and clear.
      placeholder: "API returns 500 when saving a bottle"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps (and data) needed to trigger the bug.
      placeholder: |
        1. Go to …
        2. Click …
        3. See error …
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: Expected result
      placeholder: "Bottle saves and shows up in the list"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: Include screenshots, logs, or stack traces if available.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Environment
      description: Include browser/device info or compose build details if relevant.
